FROM ubuntu:20.04

RUN apt-get update \
&& apt-get install python3-pip -y \
&& pip3 install requests==2.26.0 \
&& apt-get clean

COPY predict_model_clean_csv_test.py /app/

COPY /csv_files/test.csv /app/csv_files/

WORKDIR /app/

CMD python3 predict_model_clean_csv_test.py